### ISSUE TITLE
Add fix to handle missmatch of blankspaces in Machine model names in corrections.py

### ISSUE THREAD

**Issue by BwKodex** [rvbCMTS/PySkinDose#41]
In #27 Witty159 found an error where a TypeError is reported for the `k_tab` calculation for Allura Clarity.

After debugging I found that the error comes from the data in the underlying PySkinDose data the machine modelname is spelled _AlluraClarity_ while in the DICOM data it is spelled _Allura Clarity_ with an included blankspace.

My suggested fix is to rewrite the SQL query to handle a possible extra blank space in the name.

**Comment by MaxHellstrom** [comment]
solved in #43
