### ISSUE TITLE
annoying pydicom warning message

### ISSUE THREAD

**Issue by MaxHellstrom** [rvbCMTS/PySkinDose#50]
I get this statement from pydicom when running pyskindose. Can we suppress this message or do we need to fix anything?

`C:\Users\mahe0239\Anaconda3\envs\psd\Lib\site-packages\pydicom\valuerep.py:290: UserWarning: Invalid value for VR UI: '1.2.826.0.1.3680043.8.971.00.-2921316802724104291738658310478099'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> 
for allowed values for each VR.    
  warnings.warn(msg)`

**Comment by BwKodex** [comment]
Fix added in PR #57
